//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TermsNew.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Terms2
    {
        public int ID { get; set; }
        public Nullable<int> MOT_ID { get; set; }
        public string Headword { get; set; }
        public string Definition { get; set; }
        public string Full_form { get; set; }
        public string Abbreviations { get; set; }
        public string Synonyms { get; set; }
    }
}
